/**
 * loopback4-example-shopping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Inject, Injectable, Optional} from '@angular/core';
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpEvent,
  HttpParameterCodec,
} from '@angular/common/http';
import {CustomHttpParameterCodec} from '../encoder';
import {Observable} from 'rxjs';

import {ShoppingCart} from '../model/shoppingCart';
import {ShoppingCartItem} from '../model/shoppingCartItem';

import {BASE_PATH, COLLECTION_FORMATS} from '../variables';
import {Configuration} from '../configuration';

@Injectable({
  providedIn: 'root',
})
export class ShoppingCartControllerService {
  protected basePath = 'http://127.0.0.1:3000';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();
  public encoder: HttpParameterCodec;

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string,
    @Optional() configuration: Configuration,
  ) {
    if (configuration) {
      this.configuration = configuration;
    }
    if (typeof this.configuration.basePath !== 'string') {
      if (typeof basePath !== 'string') {
        basePath = this.basePath;
      }
      this.configuration.basePath = basePath;
    }
    this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
  }

  /**
   * @param userId
   * @param shoppingCartItem shopping cart item
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public shoppingCartControllerAddItem(
    userId: string,
    shoppingCartItem?: ShoppingCartItem,
    observe?: 'body',
    reportProgress?: boolean,
  ): Observable<ShoppingCart>;
  public shoppingCartControllerAddItem(
    userId: string,
    shoppingCartItem?: ShoppingCartItem,
    observe?: 'response',
    reportProgress?: boolean,
  ): Observable<HttpResponse<ShoppingCart>>;
  public shoppingCartControllerAddItem(
    userId: string,
    shoppingCartItem?: ShoppingCartItem,
    observe?: 'events',
    reportProgress?: boolean,
  ): Observable<HttpEvent<ShoppingCart>>;
  public shoppingCartControllerAddItem(
    userId: string,
    shoppingCartItem?: ShoppingCartItem,
    observe: any = 'body',
    reportProgress: boolean = false,
  ): Observable<any> {
    if (userId === null || userId === undefined) {
      throw new Error(
        'Required parameter userId was null or undefined when calling shoppingCartControllerAddItem.',
      );
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected:
      | string
      | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.post<ShoppingCart>(
      `${this.configuration.basePath}/shoppingCarts/${encodeURIComponent(
        String(userId),
      )}/items`,
      shoppingCartItem,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }

  /**
   * @param userId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public shoppingCartControllerGet(
    userId: string,
    observe?: 'body',
    reportProgress?: boolean,
  ): Observable<ShoppingCart>;
  public shoppingCartControllerGet(
    userId: string,
    observe?: 'response',
    reportProgress?: boolean,
  ): Observable<HttpResponse<ShoppingCart>>;
  public shoppingCartControllerGet(
    userId: string,
    observe?: 'events',
    reportProgress?: boolean,
  ): Observable<HttpEvent<ShoppingCart>>;
  public shoppingCartControllerGet(
    userId: string,
    observe: any = 'body',
    reportProgress: boolean = false,
  ): Observable<any> {
    if (userId === null || userId === undefined) {
      throw new Error(
        'Required parameter userId was null or undefined when calling shoppingCartControllerGet.',
      );
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    return this.httpClient.get<ShoppingCart>(
      `${this.configuration.basePath}/shoppingCarts/${encodeURIComponent(
        String(userId),
      )}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }

  /**
   * @param userId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public shoppingCartControllerRemove(
    userId: string,
    observe?: 'body',
    reportProgress?: boolean,
  ): Observable<any>;
  public shoppingCartControllerRemove(
    userId: string,
    observe?: 'response',
    reportProgress?: boolean,
  ): Observable<HttpResponse<any>>;
  public shoppingCartControllerRemove(
    userId: string,
    observe?: 'events',
    reportProgress?: boolean,
  ): Observable<HttpEvent<any>>;
  public shoppingCartControllerRemove(
    userId: string,
    observe: any = 'body',
    reportProgress: boolean = false,
  ): Observable<any> {
    if (userId === null || userId === undefined) {
      throw new Error(
        'Required parameter userId was null or undefined when calling shoppingCartControllerRemove.',
      );
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    const httpHeaderAccepts: string[] = [];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    return this.httpClient.delete<any>(
      `${this.configuration.basePath}/shoppingCarts/${encodeURIComponent(
        String(userId),
      )}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }

  /**
   * @param userId
   * @param shoppingCart shopping cart
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public shoppingCartControllerSet(
    userId: string,
    shoppingCart?: ShoppingCart,
    observe?: 'body',
    reportProgress?: boolean,
  ): Observable<any>;
  public shoppingCartControllerSet(
    userId: string,
    shoppingCart?: ShoppingCart,
    observe?: 'response',
    reportProgress?: boolean,
  ): Observable<HttpResponse<any>>;
  public shoppingCartControllerSet(
    userId: string,
    shoppingCart?: ShoppingCart,
    observe?: 'events',
    reportProgress?: boolean,
  ): Observable<HttpEvent<any>>;
  public shoppingCartControllerSet(
    userId: string,
    shoppingCart?: ShoppingCart,
    observe: any = 'body',
    reportProgress: boolean = false,
  ): Observable<any> {
    if (userId === null || userId === undefined) {
      throw new Error(
        'Required parameter userId was null or undefined when calling shoppingCartControllerSet.',
      );
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    const httpHeaderAccepts: string[] = [];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected:
      | string
      | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.put<any>(
      `${this.configuration.basePath}/shoppingCarts/${encodeURIComponent(
        String(userId),
      )}`,
      shoppingCart,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }
}
