/**
 * loopback4-example-shopping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Inject, Injectable, Optional} from '@angular/core';
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpEvent,
  HttpParameterCodec,
} from '@angular/common/http';
import {CustomHttpParameterCodec} from '../encoder';
import {Observable} from 'rxjs';

import {InlineObject} from '../model/inlineObject';
import {InlineResponse2001} from '../model/inlineResponse2001';
import {InlineResponse2002} from '../model/inlineResponse2002';
import {NewUser} from '../model/newUser';
import {Product} from '../model/product';
import {User} from '../model/user';

import {BASE_PATH, COLLECTION_FORMATS} from '../variables';
import {Configuration} from '../configuration';

@Injectable({
  providedIn: 'root',
})
export class UserControllerService {
  protected basePath = 'http://127.0.0.1:3000';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();
  public encoder: HttpParameterCodec;

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string,
    @Optional() configuration: Configuration,
  ) {
    if (configuration) {
      this.configuration = configuration;
    }
    if (typeof this.configuration.basePath !== 'string') {
      if (typeof basePath !== 'string') {
        basePath = this.basePath;
      }
      this.configuration.basePath = basePath;
    }
    this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
  }

  /**
   * @param newUser
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public userControllerCreate(
    newUser?: NewUser,
    observe?: 'body',
    reportProgress?: boolean,
  ): Observable<User>;
  public userControllerCreate(
    newUser?: NewUser,
    observe?: 'response',
    reportProgress?: boolean,
  ): Observable<HttpResponse<User>>;
  public userControllerCreate(
    newUser?: NewUser,
    observe?: 'events',
    reportProgress?: boolean,
  ): Observable<HttpEvent<User>>;
  public userControllerCreate(
    newUser?: NewUser,
    observe: any = 'body',
    reportProgress: boolean = false,
  ): Observable<any> {
    let headers = this.defaultHeaders;

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected:
      | string
      | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.post<User>(
      `${this.configuration.basePath}/users`,
      newUser,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }

  /**
   * @param userId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public userControllerFindById(
    userId: string,
    observe?: 'body',
    reportProgress?: boolean,
  ): Observable<User>;
  public userControllerFindById(
    userId: string,
    observe?: 'response',
    reportProgress?: boolean,
  ): Observable<HttpResponse<User>>;
  public userControllerFindById(
    userId: string,
    observe?: 'events',
    reportProgress?: boolean,
  ): Observable<HttpEvent<User>>;
  public userControllerFindById(
    userId: string,
    observe: any = 'body',
    reportProgress: boolean = false,
  ): Observable<any> {
    if (userId === null || userId === undefined) {
      throw new Error(
        'Required parameter userId was null or undefined when calling userControllerFindById.',
      );
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    return this.httpClient.get<User>(
      `${this.configuration.basePath}/users/${encodeURIComponent(
        String(userId),
      )}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }

  /**
   * @param inlineObject
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public userControllerLogin(
    inlineObject: InlineObject,
    observe?: 'body',
    reportProgress?: boolean,
  ): Observable<InlineResponse2001>;
  public userControllerLogin(
    inlineObject: InlineObject,
    observe?: 'response',
    reportProgress?: boolean,
  ): Observable<HttpResponse<InlineResponse2001>>;
  public userControllerLogin(
    inlineObject: InlineObject,
    observe?: 'events',
    reportProgress?: boolean,
  ): Observable<HttpEvent<InlineResponse2001>>;
  public userControllerLogin(
    inlineObject: InlineObject,
    observe: any = 'body',
    reportProgress: boolean = false,
  ): Observable<any> {
    if (inlineObject === null || inlineObject === undefined) {
      throw new Error(
        'Required parameter inlineObject was null or undefined when calling userControllerLogin.',
      );
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected:
      | string
      | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.post<InlineResponse2001>(
      `${this.configuration.basePath}/users/login`,
      inlineObject,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }

  /**
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public userControllerPrintCurrentUser(
    observe?: 'body',
    reportProgress?: boolean,
  ): Observable<InlineResponse2002>;
  public userControllerPrintCurrentUser(
    observe?: 'response',
    reportProgress?: boolean,
  ): Observable<HttpResponse<InlineResponse2002>>;
  public userControllerPrintCurrentUser(
    observe?: 'events',
    reportProgress?: boolean,
  ): Observable<HttpEvent<InlineResponse2002>>;
  public userControllerPrintCurrentUser(
    observe: any = 'body',
    reportProgress: boolean = false,
  ): Observable<any> {
    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    if (this.configuration.accessToken) {
      const accessToken =
        typeof this.configuration.accessToken === 'function'
          ? this.configuration.accessToken()
          : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    return this.httpClient.get<InlineResponse2002>(
      `${this.configuration.basePath}/users/me`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }

  /**
   * @param userId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public userControllerProductRecommendations(
    userId: string,
    observe?: 'body',
    reportProgress?: boolean,
  ): Observable<Array<Product>>;
  public userControllerProductRecommendations(
    userId: string,
    observe?: 'response',
    reportProgress?: boolean,
  ): Observable<HttpResponse<Array<Product>>>;
  public userControllerProductRecommendations(
    userId: string,
    observe?: 'events',
    reportProgress?: boolean,
  ): Observable<HttpEvent<Array<Product>>>;
  public userControllerProductRecommendations(
    userId: string,
    observe: any = 'body',
    reportProgress: boolean = false,
  ): Observable<any> {
    if (userId === null || userId === undefined) {
      throw new Error(
        'Required parameter userId was null or undefined when calling userControllerProductRecommendations.',
      );
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    return this.httpClient.get<Array<Product>>(
      `${this.configuration.basePath}/users/${encodeURIComponent(
        String(userId),
      )}/recommend`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }
}
