/**
 * loopback4-example-shopping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Inject, Injectable, Optional} from '@angular/core';
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpEvent,
  HttpParameterCodec,
} from '@angular/common/http';
import {CustomHttpParameterCodec} from '../encoder';
import {Observable} from 'rxjs';

import {LoopbackCount} from '../model/loopbackCount';
import {Order} from '../model/order';

import {BASE_PATH, COLLECTION_FORMATS} from '../variables';
import {Configuration} from '../configuration';

@Injectable({
  providedIn: 'root',
})
export class UserOrderControllerService {
  protected basePath = 'http://127.0.0.1:3000';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();
  public encoder: HttpParameterCodec;

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string,
    @Optional() configuration: Configuration,
  ) {
    if (configuration) {
      this.configuration = configuration;
    }
    if (typeof this.configuration.basePath !== 'string') {
      if (typeof basePath !== 'string') {
        basePath = this.basePath;
      }
      this.configuration.basePath = basePath;
    }
    this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
  }

  /**
   * @param userId
   * @param order
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public userOrderControllerCreateOrder(
    userId: string,
    order?: Order,
    observe?: 'body',
    reportProgress?: boolean,
  ): Observable<Order>;
  public userOrderControllerCreateOrder(
    userId: string,
    order?: Order,
    observe?: 'response',
    reportProgress?: boolean,
  ): Observable<HttpResponse<Order>>;
  public userOrderControllerCreateOrder(
    userId: string,
    order?: Order,
    observe?: 'events',
    reportProgress?: boolean,
  ): Observable<HttpEvent<Order>>;
  public userOrderControllerCreateOrder(
    userId: string,
    order?: Order,
    observe: any = 'body',
    reportProgress: boolean = false,
  ): Observable<any> {
    if (userId === null || userId === undefined) {
      throw new Error(
        'Required parameter userId was null or undefined when calling userOrderControllerCreateOrder.',
      );
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected:
      | string
      | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.post<Order>(
      `${this.configuration.basePath}/users/${encodeURIComponent(
        String(userId),
      )}/orders`,
      order,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }

  /**
   * @param userId
   * @param where
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public userOrderControllerDeleteOrders(
    userId: string,
    where?: string,
    observe?: 'body',
    reportProgress?: boolean,
  ): Observable<LoopbackCount>;
  public userOrderControllerDeleteOrders(
    userId: string,
    where?: string,
    observe?: 'response',
    reportProgress?: boolean,
  ): Observable<HttpResponse<LoopbackCount>>;
  public userOrderControllerDeleteOrders(
    userId: string,
    where?: string,
    observe?: 'events',
    reportProgress?: boolean,
  ): Observable<HttpEvent<LoopbackCount>>;
  public userOrderControllerDeleteOrders(
    userId: string,
    where?: string,
    observe: any = 'body',
    reportProgress: boolean = false,
  ): Observable<any> {
    if (userId === null || userId === undefined) {
      throw new Error(
        'Required parameter userId was null or undefined when calling userOrderControllerDeleteOrders.',
      );
    }

    let queryParameters = new HttpParams({encoder: this.encoder});
    if (where !== undefined && where !== null) {
      queryParameters = queryParameters.set('where', <any>where);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    return this.httpClient.delete<LoopbackCount>(
      `${this.configuration.basePath}/users/${encodeURIComponent(
        String(userId),
      )}/orders`,
      {
        params: queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }

  /**
   * @param userId
   * @param filter
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public userOrderControllerFindOrders(
    userId: string,
    filter?: string,
    observe?: 'body',
    reportProgress?: boolean,
  ): Observable<Array<Order>>;
  public userOrderControllerFindOrders(
    userId: string,
    filter?: string,
    observe?: 'response',
    reportProgress?: boolean,
  ): Observable<HttpResponse<Array<Order>>>;
  public userOrderControllerFindOrders(
    userId: string,
    filter?: string,
    observe?: 'events',
    reportProgress?: boolean,
  ): Observable<HttpEvent<Array<Order>>>;
  public userOrderControllerFindOrders(
    userId: string,
    filter?: string,
    observe: any = 'body',
    reportProgress: boolean = false,
  ): Observable<any> {
    if (userId === null || userId === undefined) {
      throw new Error(
        'Required parameter userId was null or undefined when calling userOrderControllerFindOrders.',
      );
    }

    let queryParameters = new HttpParams({encoder: this.encoder});
    if (filter !== undefined && filter !== null) {
      queryParameters = queryParameters.set('filter', <any>filter);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    return this.httpClient.get<Array<Order>>(
      `${this.configuration.basePath}/users/${encodeURIComponent(
        String(userId),
      )}/orders`,
      {
        params: queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }

  /**
   * @param userId
   * @param where
   * @param body
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public userOrderControllerPatchOrders(
    userId: string,
    where?: string,
    body?: object,
    observe?: 'body',
    reportProgress?: boolean,
  ): Observable<LoopbackCount>;
  public userOrderControllerPatchOrders(
    userId: string,
    where?: string,
    body?: object,
    observe?: 'response',
    reportProgress?: boolean,
  ): Observable<HttpResponse<LoopbackCount>>;
  public userOrderControllerPatchOrders(
    userId: string,
    where?: string,
    body?: object,
    observe?: 'events',
    reportProgress?: boolean,
  ): Observable<HttpEvent<LoopbackCount>>;
  public userOrderControllerPatchOrders(
    userId: string,
    where?: string,
    body?: object,
    observe: any = 'body',
    reportProgress: boolean = false,
  ): Observable<any> {
    if (userId === null || userId === undefined) {
      throw new Error(
        'Required parameter userId was null or undefined when calling userOrderControllerPatchOrders.',
      );
    }

    let queryParameters = new HttpParams({encoder: this.encoder});
    if (where !== undefined && where !== null) {
      queryParameters = queryParameters.set('where', <any>where);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected:
      | string
      | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.patch<LoopbackCount>(
      `${this.configuration.basePath}/users/${encodeURIComponent(
        String(userId),
      )}/orders`,
      body,
      {
        params: queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }
}
